### ISSUE TITLE
Change Proto Password and going back shows a not true message

### ISSUE THREAD

**Issue by Voetloos** [saproto/saproto#1156] opened 2020-06-08 19:53 UTC
If you click 'Change Proto password' in your dashboard, and click the back button in your browser, you get a message that the changes are saved. However, this should not happen.

**Comment by Voetloos** [comment] 2020-06-08 19:55
Same when clicking 'complete profile for membership'

**Comment by Voetloos** [comment] 2020-06-08 19:58
Same for 'Issue SEPA direct withdrawal authorisation'

**Comment by jonathanjuursema** [comment] 2020-08-25 19:31
I can't seem to reproduce this issue. Is it possible that you were trying to submit another form before you were doing this? The "changes saved" messages that you get when submitting forms are sometimes shown twice if you navigate the site in a strange way due to how sessions and these flash messages work.

**Comment by Jessseee** [comment] 2020-12-01 19:21
@jonathanjuursema did you manage to reproduce the issue, as you self assigned the issue and marked it as a bug?

**Closed by Jessseee** 2020-12-01 19:21 UTC
Labels: feedback
