### ISSUE TITLE
Helper mail nog being sent. 

### ISSUE THREAD

**Issue by Vlieking** [saproto/saproto#1048] opened 2019-12-04 10:59 UTC
Hello, 

This monday, an event was made (FriAD) which needed ERO's. However, there appeared to not have been any helper mail sent to the emergencie. (at least 3 people who have their helper mails turned on did not get it). So yeah... halp?

**Comment by jonathanjuursema** [comment] 2019-12-04 16:07
As far as I can see noone has helper reminders set for the EmergenCie. Could you send me a message on Slack with who believe their reminders should be enabled for the EmergenCie?

**Comment by jonathanjuursema** [comment] 2019-12-05 07:19
Okay so this is not the helper *reminder* emails, but instead the initial e-mails that committee members get when their committee has been picked as a helping committee.

**Comment by thijsdortmann** [comment] 2020-01-13 13:33
This is most likely caused by #1072. This has been fixed, but the fix has not yet been approved/released.

**Comment by thijsdortmann** [comment] 2020-01-13 16:43
Should be fixed now that #1072 is merged. Please reopen the issue if the problem occurs again :)

**Closed by thijsdortmann** 2020-01-13 16:43 UTC
Labels: bug, feedback
