### ISSUE TITLE
Pastries Database comeback?

### ISSUE THREAD

**Issue by TomOnderwater** [saproto/saproto#154] opened 2016-09-08 10:01 UTC
Is it possible that the pastries database gets a return? A lot of pastries have been baked during the kick-in.

**Comment by DennisVinke** [comment] 2016-09-08 10:07
It's on the to-do list of the site already!

**Comment by TomOnderwater** [comment] 2016-09-08 10:18
Tof!

**Comment by jonathanjuursema** [comment] 2016-09-08 10:32
Duplicate of #21. Please subscribe to that issue for updates. :)

**Closed by jonathanjuursema** 2016-09-08 10:32 UTC
