### ISSUE TITLE
When you copy an event, the participation count of the event is was copied from is still visible in the calender

### ISSUE THREAD

**Issue by lucer1** [saproto/saproto#2169] opened 2024-06-14 11:37 UTC
When you copy an event, the participation count of the event is was copied from is still visible in the calender

**Comment by Wilkuu-2** [comment] 2024-06-18 20:55
Duplicate of #2165

Our favourite QuickFixxer, Ysbrand is on the case.

**Closed by Wilkuu-2** 2024-06-18 20:55 UTC
