### ISSUE TITLE
drinking-tool: buy each drink separately.

### ISSUE THREAD

**Issue by renskruining** [saproto/saproto#66] opened 2016-06-08 18:53 UTC
Instead of drinking cards, buy each drink separately.

this makes life as treasurer better (:

in first instance, functionality of card reader can be missing.

**Comment by jonathanjuursema** [comment] 2016-06-21 12:05
Closed as duplicate of https://github.com/saproto/saproto/issues/29.

**Closed by jonathanjuursema** 2016-06-21 12:05 UTC
