### ISSUE TITLE
Can we have a "Shame *bell sound*" sound effect?"

### ISSUE THREAD

**Issue by JRitmeester** [saproto/saproto#929] opened 2019-03-27 15:36 UTC
We need some casual shaming now and then...

**Comment by thijsdortmann** [comment] 2019-04-02 09:15
If you can provide us with a sound you would like to use we can add it for you! :)

**Comment by jonathanjuursema** [comment] 2019-04-16 18:40
Duplicate of #936. Please re-use this issue for comments and not make a new one. ;)

**Closed by jonathanjuursema** 2019-04-16 18:40 UTC
Labels: soundboard
