### ISSUE TITLE
Flowchart page does not render properly

### ISSUE THREAD

**Issue by basRet** [saproto/saproto#2157] opened 2024-05-25 10:24 UTC
The flowchart on the website (https://www.proto.utwente.nl/page/flowcharttotal) doesn't load properly (at least on edge and firefox + safari on iphone). Only the HTML is visible. 

![image](https://github.com/saproto/saproto/assets/99681342/cf625d3c-97b4-491e-97ff-deb4ee35461c)

**Comment by Jessseee** [comment] 2024-05-26 13:46
Duplicate of #2016. The board should be able to fix this. Maybe contact the officer of eductional affairs directly.

**Closed by Jessseee** 2024-05-26 13:46 UTC
Labels: bug
