### ISSUE TITLE
Webdesign improvement: ProTube Overhaul

### ISSUE THREAD

**Issue by robi-wan69** [saproto/saproto#444] opened 2017-04-19 22:32 UTC
In a new design overhaul, ProTube will become somewhat contemporary to use. 

![1-login](https://cloud.githubusercontent.com/assets/18185955/25204698/1ba7ec10-255f-11e7-85c1-f0f94a4127da.png)
At the landing page, ProTube would now also give you the possibilities to go to the screen if you're somewhere else. You can also be redirected to the admin panel on the Proto site.
![2-loggedin](https://cloud.githubusercontent.com/assets/18185955/25204700/1cbe9554-255f-11e7-8c7d-711be84e867d.png)
When you're logged in but haven't searched anything, you'll get to know a small Proto/HYTTIOAOA fact.
![3-searching](https://cloud.githubusercontent.com/assets/18185955/25204702/1d85b724-255f-11e7-976b-7bf07245f394.png)
Searching will no longer give a list but a raster of results. Pressing the yellow 'add' button will add the media to the queue, turning the button yellow with a checkmark: it's now in the queueueue.
![4-queue](https://cloud.githubusercontent.com/assets/18185955/25204704/1e57e65e-255f-11e7-991c-8575333e5b3f.png)
Site-wide accessible is the all-new queueueue, allowing you to see what's in the queueueue at any time you're browsing the ProTube site (which isn't that big)

Notes regarding the remote:
- The switch in the top-right corner is for turning on/off the video play. Turning it on will make the switch green and increase the opacity to 100% of the video icon, while decreasing the music one to 33%. Turning it off will make it gray with the opacity adjusted in the other way around.
- The search bar is somewhat large in the mockup, this may be adjusted within testing.
- Icons are all part of the material.io/icons/ set
- Just like the design rules and styling etc

![5-screen](https://cloud.githubusercontent.com/assets/18185955/25204706/1f5b62a6-255f-11e7-81be-2e1be054d8e1.png)
The new ProTube screen will have less features than the current one. In order to get full-screen experience, the full queueueue is not anymore displayed on screen, 
A small shadow/gradient is overlaid to make sure the white text is readable, without having to implement huge drop shadows behind every item. .

Final notes: 
- Mobile layout will be worked on after approvement, just like any other ProTube screens not displayed as of now.

**Comment by jonathanjuursema** [comment] 2017-04-20 06:18
Desgins look cool! Theres only one issue: the entire website is built in Bootstrap. Is switching to Material something you want to do site wide?

**Comment by jonathanjuursema** [comment] 2017-05-15 18:29
Duplicate of https://github.com/saproto/saproto/issues/153.

**Comment by thijsdortmann** [comment] 2017-06-12 18:19
Will be implemented when the new design framework is up.

**Comment by jonathanjuursema** [comment] 2017-09-17 18:17
This issue will be closed in favor of #520, but referenced so that the design work is not lost.

**Closed by jonathanjuursema** 2017-09-17 18:17 UTC
Labels: design, to-be-implemented
