### ISSUE TITLE
OmNonCom product search field improvement

### ISSUE THREAD

**Issue by Habenga** [saproto/saproto#654] opened 2018-02-23 11:19 UTC
Would it possible to make the search field on https://www.proto.utwente.nl/omnomcom/products search not only the 'Product name' but also the 'Nicename' and the product number.
Just sequential search, without relevance and such, would be enough.

**Comment by jonathanjuursema** [comment] 2018-02-23 12:01
This is now more or less a duplicate of #655

**Closed by jonathanjuursema** 2018-02-23 12:01 UTC
