### ISSUE TITLE
Finance database overview

### ISSUE THREAD

**Issue by Athrem** [saproto/saproto#261] opened 2016-11-04 09:37 UTC
Dear HYTTIOAOA committee,

For the treasurer and his finances I would like to ask for another feature, so it can be easier for Jur to do his bookkeeping and for the audit committee to check them. 
Could you make a page which specifies the amount we receive per account (e.g. 4000 ACE, 1400 Pilscie) for a given timeframe (e.g. 13:37 4-11-2016 to 04:20 5-11-2016) both inputted by the user and is taken along in the direct withdrawal (so puraches made on the same day but not included in the direct withdrawal should not be displayed)?

Thanks in advance.

**Comment by jonathanjuursema** [comment] 2016-11-04 11:22
According to Jur there will be some additional comments for this issue, so we'll leave this issue be untill Jur provides his feedback. :)

**Comment by jonathanjuursema** [comment] 2017-02-06 21:14
Duplicate of #259

**Closed by jonathanjuursema** 2017-02-06 21:14 UTC
Labels: feature-request
