### ISSUE TITLE
Negative sound when scanning the Omnomcom NFC doesn't work

### ISSUE THREAD

**Issue by MaartjeHuveneers** [saproto/saproto#1015] opened 2019-10-28 14:56 UTC
When people scan the NFC scanner and it doesn't work, so it gives the error "Please close this window and try again" it gives the same beep as when the scanning does work. 
Conclusion: people think it has scanned correctly and walk away immediately without looking at the screen. Could the sound be changed to something more negative when it doesn't scan correctly?

**Comment by jonathanjuursema** [comment] 2019-10-28 15:06
Is this the same as #1012?

**Comment by MaartjeHuveneers** [comment] 2019-10-28 15:07
Oops yes it is

**Comment by jonathanjuursema** [comment] 2019-10-28 15:09
Closed as duplicate of #1012 :)

**Closed by jonathanjuursema** 2019-10-28 15:09 UTC
Labels: feedback
