### ISSUE TITLE
Discontinued accounts leading to own profile

### ISSUE THREAD

**Issue by robi-wan69** [saproto/saproto#824] opened 2018-10-24 18:32 UTC
I've spotted an user who's no longer member, but who's name is still a link. It however links to https://www.proto.utwente.nl/user

Because of GDPR, no names here. The profile is however in the Magazine committee, and namely in the 2017 edition of it. Good luck with this riddle!

**Comment by jonathanjuursema** [comment] 2018-10-24 19:14
Duplicate of #813

**Closed by jonathanjuursema** 2018-10-24 19:14 UTC
